VERZIJA=CDX
MODUL=pos_s1tg

SRCDOSROOT=c:\\dev\\fmk\\pos\\specif\\tigra\\1g\\

PRGS=tigra.prg mars.prg primpak.prg rpt_prpa.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
