VERZIJA=CDX
MODUL=pos_1int

SRCDOSROOT=c:\\dev\\fmk\\pos\\integ\\1g\\

PRGS=mnu_int.prg db_int.prg main.prg integ1.prg integ2.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
