VERZIJA=CDX
MODUL=POS

PRGS=../main/1g/e.prg
CS=
ASMS=

FMK_LIBS=fmk_roba.lib fmk_svi.lib fmk_pi.lib fmk_evn.lib fmk_sec.lib fmk_mes.lib fmk_rab.lib fmk_rn.lib fmk_lok.lib partnst.lib

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc1g_rpt.lib sc2g_db.lib sc2g_cui.lib sc1g_key.lib ka_s1pf.lib

MODUL_LIBS=pos_1m.lib pos_2m.lib pos_1db.lib pos_1dok.lib pos_1kal.lib pos_1prn.lib pos_1rd.lib pos_1rf.lib pos_1rpt.lib pos_1sif.lib pos_1sir.lib pos_1smj.lib pos_1sql.lib pos_1srv.lib pos_1ste.lib pos_s1ex.lib pos_s1pf.lib pos_s1tg.lib pos_2db.lib pos_1rbt.lib pos_1fis.lib pos_1epl.lib pos_1int.lib

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

