VERZIJA=CDX
MODUL=pos_1dok

SRCDOSROOT=$(BASEDOS)\\fmk\\pos\\dok\\1g\\

PRGS=frm_nar.prg frm_rac.prg frm_rrac.prg frm_zad.prg rpt_inni.prg rpt_pocs.prg rpt_raz.prg rpt_rn.prg rpt_treb.prg rpt_zad.prg frm_inni.prg mnu_rac.prg mnu_robm.prg rpt_tar.prg tarifa.prg frm_rdio.prg frm_dok.prg frm_rek.prg stolovi.prg db.prg

CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
