VERZIJA=CDX
MODUL=pos_1m

SRCDOSROOT=c:\\dev\\fmk\\pos\\main\\1g\\

PRGS=app_srv.prg dummy.prg mnu_adm.prg mnu_prod.prg mnu_upr.prg params.prg prijava.prg ut.prg zakrpe.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
