VERZIJA=CDX
MODUL=pos_1rpt

SRCDOSROOT=c:\\dev\\fmk\\pos\\rpt\\1g\\

PRGS=rpt_dkum.prg rpt_kart.prg rpt_ldok.prg rpt_part.prg rpt_por.prg rpt_pvpl.prg rpt_rkas.prg rpt_rodj.prg rpt_rrad.prg rpt_stan.prg rpt_stpm.prg rpt_top.prg mnu_real.prg mnu_izvj.prg rpt_ut.prg rpt_rkks.prg rpt_opt.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
