VERZIJA=CDX
MODUL=pos_s1pf

SRCDOSROOT=$(BASEDOS)\\fmk\\pos\\specif\\planika\\1g\\

PRGS=planika.prg promvp.prg trgk.prg rpt_tk.prg testcase.prg obuca.prg
CS=
ASMS=

include ../../../../fmk_lib/Makefile_clipper
