VERZIJA=CDX
MODUL=pos_s1pf

SRCDOSROOT=c:\\dev\\fmk\\pos\\specif\\planika\\1g\\

PRGS=planika.prg promvp.prg trgk.prg rpt_tk.prg testcase.prg obuca.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
